### ISSUE TITLE
falta arquivos

### ISSUE THREAD

**Issue by devthiagoh** [filipeportes/goevent#1]
boa tarde filipe, blz cara, então brow tava dando uma olhada no seu código do goevent de javaee com osgi e subiu blz, mais está faltando as pages evento.jsf e participante.jsf poderia disponibilizar?

**Comment by filipeportes** [comment]
olá thiago, só agora vi essa issue :(

as páginas de evento e participante estão nos módulos event e person respectivamente.
é necessário subir todos os módulos para que elas fiquem disponíveis.
